export const testUser = {
  title: "Mr",
  firstName: "Nathan",
  lastName: "Britten",
  annualIncome: "123456",
  employmentStatus: "partTime",
  houseNumber: "345",
  postcode: "GU24 8LL",
  dob: "2022-08-05",
};

export const testData = [
  {
    id: 1,
    code: "studentLife",
    name: "Student Life",
    apr: "18.9",
    balanceOffer: "0",
    purchaseOffer: "6",
    creditAvailable: "1200",
    employmentRestrictions: ["student"],
    minimumAnnualIncome: "0",
  },
  {
    id: 2,
    name: "Anywhere Card",
    code: "anywhereCard",
    apr: "33.9",
    balanceOffer: "0",
    purchaseOffer: "0",
    creditAvailable: "300",
    employmentRestrictions: [],
    minimumAnnualIncome: "0",
  },
  {
    id: 3,
    name: "Liquid Card",
    code: "liquidCard",
    apr: "33.9",
    balanceOffer: "12",
    purchaseOffer: "6",
    creditAvailable: "3000",
    minimumAnnualIncome: "16000",
    employmentRestrictions: [],
  },
];
